services:
  - type: web
    name: sugarcane-transcriptome
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn web_app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sugarcane-db
          property: connectionString

databases:
  - name: sugarcane-db
    plan: free
